"use client";

import { useCallback, useRef } from "react";

type ResultActionsProps = {
  toolTitle?: string;
};

export function ResultActions({ toolTitle = "Result" }: ResultActionsProps) {
  const wrapRef = useRef<HTMLDivElement>(null);

  const getResultBox = useCallback(() => {
    const wrap = wrapRef.current;
    if (!wrap) return null;
    return wrap.closest(".result-box, .risk-result") as HTMLElement | null;
  }, []);

  const handlePrint = useCallback(() => {
    const box = getResultBox();
    if (!box) return;

    let styles = "";
    document.querySelectorAll("style").forEach((s) => {
      styles += s.textContent;
    });

    const w = window.open("", "_blank", "width=480,height=640");
    if (!w) {
      window.alert("Please allow pop-ups to print your result.");
      return;
    }

    w.document.write(
      `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${toolTitle} — Result</title><style>` +
        styles +
        `body{padding:28px;background:#fff;font-family:inherit}` +
        `.result-actions{display:none !important}` +
        `.print-title{font-family:var(--font-display);font-size:1.1rem;font-weight:700;color:var(--gray-900);margin-bottom:14px}` +
        `.print-foot{margin-top:18px;font-size:.7rem;color:var(--gray-500,#888)}` +
        `</style></head><body>` +
        `<div class="print-title">${toolTitle}</div>` +
        box.outerHTML +
        `<div class="print-foot">Generated by The Dr Insight — drinsight.org</div>` +
        `</body></html>`,
    );
    w.document.close();
    w.onload = () => {
      w.focus();
      w.print();
    };
  }, [getResultBox, toolTitle]);

  const handleDownload = useCallback(async () => {
    const box = getResultBox();
    if (!box) return;

    try {
      const html2canvas = (await import("html2canvas")).default;
      const canvas = await html2canvas(box, { scale: 2, backgroundColor: "#ffffff" });
      const link = document.createElement("a");
      link.download = `${toolTitle.replace(/[^a-z0-9]+/gi, "_")}_result.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch {
      window.alert("Download is still loading — please try again in a moment.");
    }
  }, [getResultBox, toolTitle]);

  return (
    <div className="result-actions" ref={wrapRef}>
      <button type="button" className="result-action-btn" onClick={handlePrint}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
          <polyline points="6 9 6 2 18 2 18 9" />
          <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
          <rect x="6" y="14" width="12" height="8" />
        </svg>
        Print
      </button>
      <button type="button" className="result-action-btn" onClick={() => void handleDownload()}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
        Download
      </button>
    </div>
  );
}
