"use client";

import type { ReactNode } from "react";
import type { Icon } from "@solar-icons/react/lib/types";
import {
  Banknote,
  Bell,
  Body,
  Bolt,
  Book,
  Bookmark,
  Calendar,
  CalendarDate,
  CalendarMark,
  Card,
  ChatRound,
  ClockCircle,
  CloseCircle,
  DangerTriangle,
  DocumentText,
  Dollar,
  Eye,
  Flag,
  GraphDown,
  Health,
  HeartPulse,
  History,
  Hospital,
  Inbox,
  Letter,
  Link as LinkIcon,
  LockPassword,
  Magnifier,
  Mailbox,
  Pen,
  Phone,
  Pill,
  QuestionCircle,
  RecordCircle,
  RefreshCircle,
  Scale,
  Settings,
  ShieldCheck,
  Smartphone,
  Star,
  Stethoscope,
  TestTube,
  Upload,
  UserCrossRounded,
  UserRounded,
  UsersGroupRounded,
  VerifiedCheck,
  Videocamera,
  Wallet,
  Waterdrops,
} from "@solar-icons/react";
import { DoctorIcon, type DoctorColorTone, type DoctorIconSize } from "@/components/doctor/icons/DoctorIcons";

type EmojiIconMeta = { icon: Icon; tone?: DoctorColorTone };

const EMOJI_ICON_MAP: Record<string, EmojiIconMeta> = {
  "📊": { icon: Calendar, tone: "blue" },
  "📅": { icon: CalendarDate, tone: "indigo" },
  "🕒": { icon: ClockCircle, tone: "amber" },
  "⏳": { icon: ClockCircle, tone: "amber" },
  "⏱️": { icon: ClockCircle, tone: "blue" },
  "✅": { icon: VerifiedCheck, tone: "success" },
  "❌": { icon: CloseCircle, tone: "error" },
  "⛔": { icon: UserCrossRounded, tone: "error" },
  "💬": { icon: ChatRound, tone: "cyan" },
  "📬": { icon: Mailbox, tone: "cyan" },
  "📨": { icon: Inbox, tone: "cyan" },
  "📧": { icon: Letter, tone: "gray" },
  "✉️": { icon: Letter, tone: "gray" },
  "💰": { icon: Wallet, tone: "gold" },
  "💳": { icon: Card, tone: "indigo" },
  "🏦": { icon: Banknote, tone: "gold" },
  "🩺": { icon: Stethoscope, tone: "blue" },
  "👨‍⚕️": { icon: Stethoscope, tone: "blue" },
  "📰": { icon: DocumentText, tone: "orange" },
  "📝": { icon: Pen, tone: "orange" },
  "📦": { icon: Book, tone: "orange" },
  "📚": { icon: Book, tone: "orange" },
  "⭐": { icon: Star, tone: "amber" },
  "👥": { icon: UsersGroupRounded, tone: "purple" },
  "🧑‍🤝‍🧑": { icon: UserRounded, tone: "purple" },
  "🛡️": { icon: ShieldCheck, tone: "blue" },
  "📜": { icon: History, tone: "indigo" },
  "🛠️": { icon: Settings, tone: "gray" },
  "🔓": { icon: LockPassword, tone: "amber" },
  "🚨": { icon: DangerTriangle, tone: "warning" },
  "⚠️": { icon: DangerTriangle, tone: "warning" },
  "🚩": { icon: Flag, tone: "error" },
  "🔔": { icon: Bell, tone: "gray" },
  "📱": { icon: Smartphone, tone: "gray" },
  "❓": { icon: QuestionCircle, tone: "blue" },
  "🔖": { icon: Bookmark, tone: "orange" },
  "🔬": { icon: TestTube, tone: "teal" },
  "🔄": { icon: RefreshCircle, tone: "blue" },
  "📤": { icon: Upload, tone: "cyan" },
  "👁️": { icon: Eye, tone: "gray" },
  "📉": { icon: GraphDown, tone: "red" },
  "🟢": { icon: RecordCircle, tone: "green" },
  "🏁": { icon: CalendarMark, tone: "success" },
  "🔍": { icon: Magnifier, tone: "gray" },
  "🔎": { icon: Magnifier, tone: "gray" },
  "🔗": { icon: LinkIcon, tone: "blue" },
  "🧬": { icon: TestTube, tone: "teal" },
  "💊": { icon: Pill, tone: "red" },
  "❤️": { icon: HeartPulse, tone: "red" },
  "🩸": { icon: Waterdrops, tone: "red" },
  "🫁": { icon: Health, tone: "teal" },
  "🧠": { icon: Body, tone: "purple" },
  "⚖️": { icon: Scale, tone: "blue" },
  "🔧": { icon: Bolt, tone: "warning" },
  "🏥": { icon: Hospital, tone: "indigo" },
  "⚕️": { icon: Health, tone: "teal" },
  "💵": { icon: Dollar, tone: "gold" },
  "📞": { icon: Phone, tone: "cyan" },
  "🎥": { icon: Videocamera, tone: "cyan" },
};

export function resolveEmojiIcon(value: string, size: DoctorIconSize = "stat"): ReactNode {
  const meta = EMOJI_ICON_MAP[value];
  if (!meta) return value;
  return <DoctorIcon icon={meta.icon} size={size} tone={meta.tone} />;
}

export function resolveDashboardIcon(value: ReactNode, size: DoctorIconSize = "stat"): ReactNode {
  if (typeof value === "string") return resolveEmojiIcon(value, size);
  return value;
}
