import { z } from "zod";

export const adminDoctorProfileSchema = z.object({
  fullName: z.string().min(2, "Full name is required"),
  credentials: z.string().optional(),
  specialty: z.string().min(1, "Specialty is required"),
  specLabel: z.string().optional(),
  photoIcon: z.string().optional(),
  experience: z.string().optional(),
  title: z.string().optional(),
  institution: z.string().optional(),
  location: z.string().optional(),
  email: z.string().email("Enter a valid email").optional().or(z.literal("")),
  phone: z.string().optional(),
  license: z.string().optional(),
  regBody: z.string().optional(),
  languages: z.string().optional(),
  responseTime: z.string().optional(),
  expertise: z.string().optional(),
  bioShort: z.string().optional(),
  bioFull: z.string().optional(),
  education: z.string().optional(),
  boardCerts: z.string().optional(),
  awards: z.string().optional(),
  lectures: z.string().optional(),
  coiDeclaration: z.string().optional(),
  coiUpdated: z.string().optional(),
  roleAuthorSince: z.string().optional(),
  roleEditorialBoard: z.string().optional(),
  roleReviewerFor: z.string().optional(),
  facebook: z.string().optional(),
  twitter: z.string().optional(),
  youtube: z.string().optional(),
  instagram: z.string().optional(),
  linkedin: z.string().optional(),
  seoFocus: z.string().optional(),
  seoSecondary: z.string().optional(),
  metaTitle: z.string().max(70, "Meta title should be 60 characters or fewer").optional(),
  metaDesc: z.string().max(170, "Meta description should be 160 characters or fewer").optional(),
  seoUrl: z.string().optional(),
  schema: z.string().optional(),
  avatarUrl: z.string().optional(),
});

export type AdminDoctorProfileFormValues = z.infer<typeof adminDoctorProfileSchema>;
