/** Canonical medical specialty options for doctor profiles, articles, and research forms. */
export const MEDICAL_SPECIALTIES = [
  "Allergy & Immunology",
  "Anesthesiology",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Clinical Psychology",
  "Colorectal Surgery",
  "Critical Care Medicine",
  "Dental & Oral Health",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "ENT / Otolaryngology",
  "Family Medicine",
  "Gastroenterology",
  "General Medicine",
  "General Surgery",
  "Geriatric Medicine",
  "Gynecology",
  "Hematology",
  "Hepatology",
  "Infectious Disease",
  "Internal Medicine",
  "Interventional Radiology",
  "Medical Genetics",
  "Medical Oncology",
  "Neonatology",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Nutrition & Dietetics",
  "Obstetrics",
  "Obstetrics & Gynecology (OB/GYN)",
  "Occupational Medicine",
  "Oncology",
  "Ophthalmology",
  "Oral & Maxillofacial Surgery",
  "Orthopedics",
  "Pain Medicine",
  "Palliative Care",
  "Pathology",
  "Pediatrics",
  "Pediatric Surgery",
  "Physical Medicine & Rehabilitation",
  "Plastic Surgery",
  "Podiatry",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonology",
  "Radiation Oncology",
  "Radiology",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Surgical Oncology",
  "Transplant Surgery",
  "Trauma Surgery",
  "Urology",
  "Vascular Surgery",
  "Other",
] as const;

export type MedicalSpecialty = (typeof MEDICAL_SPECIALTIES)[number];
